version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-auto-publisher
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTS_FILE=/app/data/posts.json
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    networks:
      - telegram-bot-network

networks:
  telegram-bot-network:
    driver: bridge
